RatingsConvert = {
    "SPRatings": {
        "AA+": "AA",
        "AA": "AA",
        "NR": "NR",
        "A": "A",
        "AAA": "AAA",
        "AA-": "AA",
        "BBB": "BBB",
        "BB+": "BB",
        "BB": "BB",
        "BBB+": "BBB",
        "A-1+": "A",
        "BB-": "BB",
        "BBB-": "BBB",
        "B": "B",
        "B+": "B",
        "A+": "A",
        "A-": "A",
        "A-1": "A",
        "B-": "B",
    },
    "DBRSRatings": {
        "AAA": "AAA",
        "A": "A",
        "AA": "AA",
        "A (H)": "A",
        "R-1 H": "AAA",
        "BBB": "BBB",
        "BB": "BB",
        "AA (H)": "AA",
        "BBB (H)": "BBB",
        "BB (H)": "BB",
        "B (H)": "B",
        "BB (L)": "BB",
        "NR": "NR",
        "B": "B",
        "BBB (L)": "BBB",
        "AA (L)": "AA",
        "A (L)": "A",
        "B (L)": "B",
        "R-1 M": "AAA",
    },
    "MoodysRatings": {
        "Aaa": "AAA",
        "A2": "A",
        "A3": "A",
        "Aa1": "AA",
        "Aa2": "AA",
        "A1": "A",
        "P-1": "AAA",
        "Baa3": "BBB",
        "Aa3": "AA",
        "Baa2": "BBB",
        "NR": "NR",
        "Baa1": "BBB",
        "B2": "B",
        "B3": "B",
        "Ba2": "BB",
        "Ba3": "BB",
        "B1": "B",
        "Ba1": "BB",
    },
    "FitchRatings": {
        "AAA": "AAA",
        "NR": "NR",
        "A": "A",
        "BBB": "BBB",
        "AA": "AA",
        "A+": "A",
        "A-": "A",
        "AA-": "AA",
        "BB": "BB",
        "BBB-": "BBB",
        "F1+": "AAA",
        "BB-": "BB",
        "AA+": "AA",
        "F1": "AAA",
        "B": "B",
        "BBB+": "BBB",
        "BB+": "BB",
        "B+": "B",
        "B-": "B",
    },
    "KBRARatings": {
        "AA-": "AA",
        "A-": "A",
        "BBB-": "BBB",
        "BB-": "BB",
        "A": "A",
        "BBB+": "BBB",
        "BB+": "BB",
        "BBB": "BBB",
        "BB": "BB",
        "A+": "A",
        "B+": "B",
        "B": "B",
        "NR": "NR",
        "AA": "AA",
        "AAA": "AAA",
        "K1+": "AAA",
        "AA+": "AA",
        "B-": "B",
    },
    "RatingsRank": {
        "AAA": 1,
        "AA": 2,
        "A": 3,
        "BBB": 4,
        "BB": 5,
        "B": 6,
        "CCC": 7,
        "CC": 8,
        "C": 9,
        "NR": 9999,
    },
}
